version: '3.3'

services:
  mysqldb:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: pageviewservice
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  myrabbitmq:
    image: rabbitmq
    ports:
      - "5671:5671"
      - "5672:5672"
  pageviewservice:
    image: springframeworkguru/pageviewservice
    ports:
      - "8081:8081"
#    restart: always
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysqldb:3306/pageviewservice?useSSL=false'
      SPRING_PROFILES_ACTIVE: 'mysql'
      SPRING_RABBITMQ_HOST: myrabbitmq
    depends_on:
      mysqldb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3




