version: '3.3'

services:

  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: pageviewservice
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s
      timeout: 20s
      retries: 10

  myrabbitmq:
    image: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  pageviewservice:
    image: springframeworkguru/pageviewservice
#    restart: always
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysqldb:3306/pageviewservice?useSSL=false'
      SPRING_PROFILES_ACTIVE: 'mysql'
      SPRING_RABBITMQ_HOST: myrabbitmq
    depends_on:
      mysqldb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  spring-boot-docker:
    image: artarkatesoft/springbootdocker
    ports:
      - '8080:8080'
    environment:
      SPRING_RABBITMQ_HOST: myrabbitmq
    depends_on:
      myrabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3


